### ISSUE TITLE
Docker not working with android devices

### ISSUE THREAD

**Issue by TomMar71** [TonyTromp/tidal-connect-docker#29]
The installation seems to have worked fine as Tidal connect works as intended from my Windows PC, however when I try and select the Device (which does show up) on my Android 10 Tablet it just stops playback. When I press resume it automatically jumps back to the Tablet speakers.

**Comment by TomMar71** [comment]
just read the previous issue thread, probably the same issue

**Comment by Kybeer** [comment]
Same issues here

**Comment by dzavux** [comment]
It did not lasted very long. This mourning I was able to use Tidal connect, Later it stopped. I can still find Tidal connect end point, but no sound.

**Comment by RalpinMcDjango** [comment]
I also have this issue running Android 12 and the Official Tidal app.

The device will appear in the list of available devices then once you select it fails to connect instantly and "disconnects" the stream.

**Comment by TonyTromp** [comment]
This is related to this error: https://github.com/TonyTromp/tidal-connect-docker/issues/28
